#!/usr/bin/env node
/**
 * build-tokens.js
 *
 * DTCG-design-token JSON generator → CSS custom properties.
 *
 * Reads every *.json file in design-tokens/ and emits
 * frontend/src/styles/tokens.css with flattened :root variables.
 *
 * Usage:  npm run build:tokens   (see package.json -> scripts)
 *
 * Token JSON format (DTCG-style):
 *   {
 *     "category": {
 *       "item": { "value": "#hex", "type": "color" }
 *     }
 *   }
 *
 * Nested groups produce dash-separated names:
 *   color.brand.orange  →  --color-brand-orange
 */
'use strict'

import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const ROOT = join(__dirname, '..')
const TOKENS_DIR = join(ROOT, 'design-tokens')
const OUTPUT_FILE = join(ROOT, 'frontend/src/styles/tokens.css')

/**
 * Category prefixes that must NOT appear in the emitted variable name.
 * The category is a grouping artefact of the JSON, not part of the token's
 * identity — components expect --header-height, not --dimension-header-height.
 * Without this, the layout tokens are unreachable from CSS.
 *
 * NOTE: safe-area is intentionally NOT stripped — CSS convention is
 * --safe-area-inset-bottom (env() counterpart), so the category is real.
 */
const STRIP_CATEGORY_PREFIX = new Set(['dimension', 'layout', 'sizing'])

/**
 * Recursively flatten a token object into [name, value] pairs.
 * @param {object} obj  - the (sub-)object to flatten
 * @param {string[]} parts - accumulated path segments
 * @param {Array<[string, string, string]>} out - accumulator [flatName, value, type]
 */
function flatten(obj, parts, out) {
  for (const [key, node] of Object.entries(obj)) {
    if (key === '$metadata') continue

    if (node && typeof node === 'object' && node.value !== undefined) {
      // Leaf token: has { value, type, description? }
      const val = String(node.value)
      const flatName = parts.concat(key).join('-')

      // Handle the "DEFAULT" key convention (e.g. color.primary.DEFAULT)
      const finalName = key === 'DEFAULT' ? parts.join('-') : flatName

      out.push([finalName, val, node.type || 'unknown'])
    } else if (node && typeof node === 'object') {
      // Group: recurse deeper
      const nextParts = key === 'DEFAULT' ? parts : parts.concat(key)
      flatten(node, nextParts, out)
    }
  }
}

/**
 * Explicit token renames. Some token names in design-tokens/*.json follow the
 * DTCG grouping convention but the CSS variable consumers rely on a different
 * canonical name (e.g. useDesktopScale.js sets --desktop-scale, not --scale-desktop).
 * Map source-flattened name → emitted CSS variable name.
 */
const TOKEN_ALIASES = {
  'scale-desktop': 'desktop-scale',
  'scale-desktop-min': 'desktop-scale-min',
  'scale-desktop-step': 'desktop-scale-step',
}

function stripCategoryPrefix(name) {
  if (TOKEN_ALIASES[name]) return TOKEN_ALIASES[name]
  const head = name.split('-')[0]
  if (STRIP_CATEGORY_PREFIX.has(head) && name.split('-').length > 1) {
    return name.slice(head.length + 1)
  }
  return name
}

/**
 * CSS custom property names may not contain '.' (invalid: --spacing-1.5).
 * Normalize fractional numeric segments to a safe dash-free form so Tailwind's
 * own spacing scale (--spacing defined once, utilities reference it) is not
 * shadowed by broken per-step variables. 1.5 → 1_5.
 */
function sanitizeNumericSegments(name) {
  return name
    .split('-')
    .map((seg) => (seg.includes('.') && /^\d+(\.\d+)?$/.test(seg) ? seg.replace('.', '_') : seg))
    .join('-')
}

function main() {
  const tokenFiles = readdirSync(TOKENS_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort()

  const allTokens = [] // { name, value, type, source }

  for (const file of tokenFiles) {
    const fullPath = join(TOKENS_DIR, file)
    const data = JSON.parse(readFileSync(fullPath, 'utf8'))
    const flat = []
    flatten(data, [], flat)

    for (const [name, value, type] of flat) {
      allTokens.push({ name, value, type, source: file })
    }
  }

  // Sort by name for readability
  allTokens.sort((a, b) => a.name.localeCompare(b.name))

  // Build CSS
  const lines = [
    '/**',
    ' * tokens.css — AUTO-GENERATED by scripts/build-tokens.js',
    ' * Do not edit by hand. Edit design-tokens/*.json and run `npm run build:tokens`.',
    ` * Generated: ${new Date().toISOString()}`,
    ' */',
    '',
    ':root {',
  ]

  for (const t of allTokens) {
    lines.push(`  --${sanitizeNumericSegments(stripCategoryPrefix(t.name))}: ${t.value};`)
  }

  lines.push('}')

  mkdirSync(dirname(OUTPUT_FILE), { recursive: true })
  writeFileSync(OUTPUT_FILE, lines.join('\n') + '\n')

  console.log(`✓ Generated ${allTokens.length} tokens → ${OUTPUT_FILE}`)
  console.log(`  Sources: ${tokenFiles.join(', ')}`)
}

main()
